Cosmetic changes, read comments
dsodx/telegram-bot-template pull request #1
Opened 2023-06-18 16:46 UTC by DiorDS

Pls, write comments:
"Your code has been rated at 3.88/10"

Change dp -> dispatcher (you should use snake_case)

Static data should be tuple NOT list.
`def get_default_commands() -> tuple[BotCommand]:
    return (
        BotCommand(command="start", description="Restart the bot"),
    )`

2023-06-18 16:55 UTC, dsodx requested changes

2023-06-18 16:55 UTC, dsodx commented on bot/__main__.py
> +    dispatcher.include_routers(*get_routers())
так никто не делает) все пишут `dp`

2023-06-18 16:55 UTC, dsodx commented on bot/handlers/__init__.py
> +    ) # bad practice but works
напиши по-подробнее

2023-06-18 16:55 UTC, dsodx commented on bot/ui/commands.py
> +def get_default_commands() -> tuple[BotCommand]:
аиограм требует list
см. https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/client/bot.py#L3236

2023-06-18 16:56 UTC, DiorDS commented on bot/__main__.py
> +    dispatcher.include_routers(*get_routers())
Это да, но с точки зрения чистого кода это неправильно)

2023-06-18 16:57 UTC, DiorDS commented on bot/handlers/__init__.py
> +    ) # bad practice but works
тут не поменять ничего по этому смысла нет обсуждать

2023-06-18 16:57 UTC, DiorDS commented on bot/ui/commands.py
> +def get_default_commands() -> tuple[BotCommand]:
а лан

2023-06-19 08:12 UTC, dsodx commented
Sorry

2023-06-19 08:12 UTC, closed without merging